#!/usr/bin/env sh

RESET="^d^"

BLOCK_TEXT="$1"
[ -z "$BLOCK_TEXT" ] && exit 1

FG_COLOR="$2"
[ -n "$FG_COLOR" ] && FG_COLOR="^c$FG_COLOR^"

if [ -e $XDG_CONFIG_HOME/shell/theme.sh ]; then
    . $XDG_CONFIG_HOME/shell/theme.sh
    BORDER_COLOR="^c${BACKGROUND_BRIGHT_COLOR}^"
fi

printf '%s\n' "${BORDER_COLOR}[${RESET} ${FG_COLOR}${BLOCK_TEXT}${RESET} ${BORDER_COLOR}]${RESET}" 
