#!/usr/bin/env sh

if ! command -v newsboat >/dev/null; then 
    exit
fi 

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"

unread=$(newsboat -x print-unread | cut -d ' ' -f 1)
echo "$unread unread"
newsboat -x reload

unread=$(( $(newsboat -x print-unread | cut -d ' ' -f 1) - unread ))
echo "$unread new unread"
if [ $unread -gt 0 ] && command -v notify-send >/dev/null; then 
    notify-send \
        "RSS Feed updated" \
        "$unread new posts" \
        -i rss 
fi

pkill -RTMIN+10 dwmblocks 
