#!/usr/bin/env sh

_upd_dwmblocks() {
    pkill -RTMIN+10 dwmblocks 
}

for arg in "$@"; do
    if [ "$arg" = "-x" ]; then 
      skip=1
    fi
done

if [ -z "$skip" ]; then 
    trap _upd_dwmblocks EXIT INT TERM
fi 

/usr/bin/newsboat "$@"
