#!/usr/bin/env sh

if ! command -v mpc >/dev/null; then 
    printf '\0'
    exit 0
fi

case "$BLOCK_BUTTON" in 
    1) mpc toggle ;;
esac

song="$(mpc --format "%title% - %artist%" current)"
if [ -n "${song}" ]; then 
    icon="$(mpc status "%state%" | sed 's/playing//;s/paused//;s/stopped//')"
    _dwm-block-2d "${icon} ${song}"
else 
    printf '\0'
fi
