#!/usr/bin/env sh

if ! command -v bluetoothctl >/dev/null; then 
    printf '\0'
    exit 0
fi

case "$BLOCK_BUTTON" in 
    1) rofi-bluetooth main ;;
esac

if "$(bluetoothctl show \
    | sed "s/^\s*// ; s/yes/true/; s/no/false/" \
    | grep "Powered:" \
    | cut -d ' ' -f 2)"; then 

    connected_count=0
    for device_id in $(bluetoothctl devices \
        | grep "^Device:" \
        | cut -d ' ' -f 2); do 

        if bluetoothctl info "$device_id" \
            | grep -q "Connected: yes"; then 

            connected_count=$((connected_count + 1))
        fi
    done 

    if [ "$connected_count" -gt 0 ]; then
        _dwm-block-2d "󰂱 $connected_count"
    else 
        _dwm-block-2d "󰂯"
    fi
else 
    _dwm-block-2d "󰂲"; 
fi 
